trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "##vso[task.setvariable variable=FlutterPath]$(PWD)/flutter"

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH="$PATH:$(FlutterPath)/bin"
        flutter pub get
        flutter build web --release

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Configure Git for GitHub Pages deployment
        git config user.name "pcoderch"
        git config user.email "pau.coderch@clearpeaks.com"

        # Navigate to the web build folder
        cd build/web

        # Initialize a new Git repository
        git init
        git remote add origin https://pcoderch:$(GITHUB_TOKEN)@github.com/pcoderch/cicd_web.git
        git checkout -b gh-pages

        # Add and commit the built web app files
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Push the build to the gh-pages branch
        git push -u origin gh-pages --force
