trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Install Python (optional, if needed for Python dependencies)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - task: FlutterInstall@0
    displayName: 'Flutter Install'
  
  - task: FlutterCommand@0
    displayName: 'Flutter Command'
    inputs:
      arguments: 'config --enable-web'


  - task: FlutterCommand@0
    displayName: 'flutter run build web'
    inputs:
      arguments: 'build web'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Set Git user information for the commit
        git config --global user.name "paucoderch"
        git config --global user.email "pau.coderch@clearpeaks.com"

        # Navigate to the web build folder
        cd build/web

        # Initialize a new Git repository
        git init

        # Set up GitHub authentication using the GITHUB_TOKEN secret
        git remote add origin https://paucoderch:$GITHUB_TOKEN@github.com/paucoderch/cicd_web.git
        git checkout -b gh-pages

        # Add and commit the built web app files
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Push the build to the gh-pages branch
        git push --set-upstream origin gh-pages --force

    displayName: 'Deploy to GitHub Pages'
