trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:

  - task: FlutterInstall@0
    displayName: 'Flutter Install'
  
  - task: FlutterCommand@0
    displayName: 'Flutter Command'
    inputs:
      arguments: 'config --enable-web'


  - task: FlutterCommand@0
    displayName: 'flutter run build web'
    inputs:
      arguments: 'build web'

  - task: vercel-deployment-task@1
    inputs:
      vercelProjectId: 'prj_65elMB5iDZ9CyrxzjSNwocP1zyte'
      vercelOrgId: 'bNF0eApoMVopLiExErs2kW1Q'
      vercelToken: 'KDXob5kMsrOBe0awwBfvEnZQ'
      production: true