trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  # Step 1: Install Python (optional, if needed for Python dependencies)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Step 2: Install Flutter SDK
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        sudo apt-get update
        sudo apt-get install -y git curl unzip xz-utils
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "##vso[task.setvariable variable=FlutterPath]$(PWD)/flutter"
        export PATH=$(FlutterPath)/bin:$PATH
        flutter/bin/flutter doctor
    displayName: 'Install Flutter SDK'

  # Step 3: Install Flutter dependencies
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH=$(FlutterPath)/bin:$PATH
        flutter pub get
    displayName: 'Install Flutter dependencies'

  # Step 4: Build the Flutter web project
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH=$(FlutterPath)/bin:$PATH
        flutter build web --release
    displayName: 'Build Flutter Web'

  # Step 5: Deploy to GitHub Pages
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH=$(FlutterPath)/bin:$PATH
        git config user.name "pcoderch"
        git config user.email "pau.coderch@clearpeaks.com"

        # Navigate to the web build folder
        cd build/web

        # Initialize a new Git repository
        git init
        git remote add origin https://pcoderch:$(GITHUB_TOKEN)@github.com/pcoderch/cicd_web.git
        git checkout -b gh-pages

        # Add and commit the built web app files
        git add .
        git commit -m "Deploy to GitHub Pages"

        # Push the build to the gh-pages branch
        git push -u origin gh-pages --force
    displayName: 'Deploy to GitHub Pages'
