trigger:
  branches:
    include:
      - main  # Trigger on the main branch

pool:
  vmImage: 'ubuntu-latest'  # You can also use macOS if needed

steps:
  - task: UsePythonVersion@0   # Required for installing Flutter dependencies
    inputs:
      versionSpec: '3.x'
      addToPath: true

  # Install Flutter SDK
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        # Download the Flutter SDK
        git clone https://github.com/flutter/flutter.git -b stable --depth 1
        echo "##vso[task.setvariable variable=FlutterPath]$(PWD)/flutter"
        echo "Flutter SDK installed at $(PWD)/flutter"
  
  # Set up Flutter in the PATH
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH="$PATH:$(FlutterPath)/bin"
        flutter --version  # Verify Flutter installation

  # Install dependencies (Flutter packages)
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH="$PATH:$(FlutterPath)/bin"
        flutter pub get

  # Run Flutter tests (Optional)
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH="$PATH:$(FlutterPath)/bin"
        flutter test

  # Build Flutter Web app
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        export PATH="$PATH:$(FlutterPath)/bin"
        flutter build web --release

  # Publish the build artifact
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: 'build/web'
      artifactName: 'FlutterWebApp'
      publishLocation: 'pipeline'
